"""empty message

Revision ID: 31be4730b3d9
Revises: 
Create Date: 2022-05-15 17:50:26.298877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31be4730b3d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sedes', sa.Column('list_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sedes', 'listas', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sedes', type_='foreignkey')
    op.drop_column('sedes', 'list_id')
    # ### end Alembic commands ###
